---

- name: buy predicted coin(s)
  hosts: localhost
  gather_facts: false
  vars_files:
     - ./defaults/main.yml
  
  tasks:

    - name: "set binance URL endpoint to {{ ba_endpoint }}"
      ansible.builtin.uri:
        url: "{{ ba_api_url }}/endpoint"
        method: POST
        body_format: json
        validate_certs: "{{ ba_validate_certs }}"
        body: "{{ ba_endpoint | to_json }}"
    
    - name: set apikey and apisecret
      ansible.builtin.uri:
        url: "{{ ba_api_url }}/apikey"
        method: POST
        body_format: json
        validate_certs: "{{ ba_validate_certs }}"
        body: "{{ ba_api_key | to_json }}"
      #no_log: true

    - name: "get prediction action for coin {{ ba_coin }}"
      ansible.builtin.uri:
        url: "{{ ba_api_url }}/coin_action"
        method: POST
        validate_certs: "{{ ba_validate_certs }}"
        body_format: json
        body: "{{ ba_coin_action | to_json }}"
        return_content: true
      register: _action
    
    - debug: 
        var: _action
        verbosity: 2
  
    - name: "order if prediction is buy"
      ansible.builtin.uri:
        url: "{{ ba_api_url }}/buy"
        body: "{{ ba_coin_buy | to_json }}"
        method: POST
        validate_certs: "{{ ba_validate_certs }}"
        body_format: json
        return_content: true
      register: _buy
      when: _action.json[ba_coin] == 'Buy'
  
    - debug: 
        var: _buy
        verbosity: 2
      when: _action.json[ba_coin] == 'Buy'

    - name: "order if prediction is sell"
      ansible.builtin.uri:
        url: "{{ ba_api_url }}/sell"
        body: "{{ ba_coin_buy | to_json }}"
        method: POST
        validate_certs: "{{ ba_validate_certs }}"
        body_format: json
        return_content: true
      register: _sell
      when: _action.json[ba_coin] == 'Sell'

    - debug: 
        var: _sell
        verbosity: 2
      when: _action.json[ba_coin] == 'Sell'

    - name: clear api key and secret
      ansible.builtin.uri:
        url: "{{ ba_api_url }}/clearkey"
        method: GET