---
- name: set cachable facts
  hosts: all
  gather_facts: false
  
  tasks:
    
    - name: cache average and total_qty
      ansible.builtin.set_fact:
        average: "{{ input_average | float }}"
        total_qty: "{{ input_total_qty | float }}"
        cacheable: true
